----
title: 在 Asciidoc 文档中使用 latex
categories:
- 备忘
- Asciidoctor
tags:
- Asciidoctor
- 线性代数
----

= 在 Asciidoc 文档中使用 latex【线性代数篇】
:stem: latexmath
:icons: font

本文基于 asciidoctor 1.5.7.13，其通过 mathjax 实现 LaTex 字体的显示，方法和 markdown 差不多，区别是 markdown（不同差距实现方法不同）使用 +$$+ 或者 +$``$+ 包围 LaTex 语法，而 asciidoctor 使用 +stem:[]+ 包围 LaTex 语法。


.单个符号对照表
|===
|渲染后 |源码
| stem:[\cdot] |+stem:[\cdot]+
| stem:[\times] |+stem:[\times]+
| stem:[a^{\prime} a] | +stem:[a^{\prime} a]+
| stem:[a’’] | +stem:[a’’]+
| stem:[\hat{a}] | +stem:[\hat{a}]+
| stem:[\bar{a}] | +stem:[\bar{a}]+
| stem:[\grave{a}] | +stem:[\grave{a}]+
| stem:[\acute{a}] | +stem:[\acute{a}]+
| stem:[\dot{a}] | +stem:[\dot{a}]+
| stem:[\ddot{a}] | +stem:[\ddot{a}]+
| stem:[\not{a}] | +stem:[\not{a}]+
| stem:[\mathring{a}] | +stem:[\mathring{a}]+
| stem:[\overrightarrow{AB}] | +stem:[\overrightarrow{AB}]+
| stem:[\overleftarrow{AB}] | +stem:[\overleftarrow{AB}]+
| stem:[a’’’] | +stem:[a’’’]+
| stem:[\overline{aaa}] | +stem:[\overline{aaa}]+
| stem:[\check{a}] | +stem:[\check{a}]+
| stem:[\vec{a}] | +stem:[\vec{a}]+
| stem:[\underline{a}] | +stem:[\underline{a}]+
| stem:[\color{red}x] | +stem:[\color{red}x]+
| stem:[\pm] | +stem:[\pm]+
| stem:[\mp] | +stem:[\mp]+
| stem:[\int y \mathrm{d}x] | +stem:[\int y \mathrm{d}x]+
| stem:[!] | +stem:[!]+
| stem:[\int y\, \mathrm{d}x] | +stem:[\int y\, \mathrm{d}x]+
| stem:[\dots] | +stem:[\dots]+
| stem:[\ldots] | +stem:[\ldots]+
| stem:[\cdots] | +stem:[\cdots]+
| stem:[\vdots] | +stem:[\vdots]+
| stem:[\ddots] | +stem:[\ddots]+
|===


.行列式
[cols= "3a,3a"]
|===
|渲染后 |源码

|[stem]
++++
\vec{a} =
 \left[\begin{array}{rrrr}
   15\\
   7
 \end{array}\right)
++++
|[source,latex]
----
\vec{a} =
\left[\begin{array}{rrrr}  <1>
  15\\
  7
\end{array}\right)         <2>
----


|[latexmath]
++++
\begin{cases}
 \ u_{tt}(x,t)= b(t)\triangle u(x,t-4)&\\
\ \hspace{42pt}- q(x,t)f[u(x,t-3)]+te^{-t}\sin^2 x,  &  t \neq t_k; \\
 \ u(x,t_k^+) - u(x,t_k^-) = c_k u(x,t_k), & k=1,2,3\ldots ;\\
 \ u_{t}(x,t_k^+) - u_{t}(x,t_k^-) =c_k u_{t}(x,t_k), &
 k=1,2,3\ldots\ .
\end{cases}
]
++++
|[source,latex]
----
[latexmath]
++++
\begin{cases}
 \ u_{tt}(x,t)= b(t)\triangle u(x,t-4)&\\
\ \hspace{42pt}- q(x,t)f[u(x,t-3)]+te^{-t}\sin^2 x,  &  t \neq t_k; \\
 \ u(x,t_k^+) - u(x,t_k^-) = c_k u(x,t_k), & k=1,2,3\ldots ;\\
 \ u_{t}(x,t_k^+) - u_{t}(x,t_k^-) =c_k u_{t}(x,t_k), &
 k=1,2,3\ldots\ .
\end{cases}
]
++++
----


|[latexmath]
++++
q(x,t)=
\begin{cases}(t-k+1)x^2,\quad \ \ &
  t\in\big(k-1,k-\dfrac{1}{2}\big],\\
  (k-t)x^2, \quad \ \ & t\in\big(k-\dfrac{1}{2},k\big],
\end{cases}
++++
|[source,latex]
----
q(x,t)=
\begin{cases}(t-k+1)x^2,\quad \ \ &
  t\in\big(k-1,k-\dfrac{1}{2}\big],\\
  (k-t)x^2, \quad \ \ & t\in\big(k-\dfrac{1}{2},k\big],
\end{cases}
----
|===


== hexo中集成asciidoctor后渲染latex的bug

hexo, asciidoctor, latex 三者在一起组成了一个很小众的东西。实际上使用 ruby 安装的 asciidoctor 在使用起来完全没有问题，但是 hexo 中因为使用的是 nodejs 中的一个 link:https://github.com/hcoona/hexo-renderer-asciidoc/[hexo-renderer-asciidoc] 插件对 hexo 增强了 asciidoctor 的功能，并且该插件会对 `{` `}` 进行 link:https://github.com/hcoona/hexo-renderer-asciidoc/blob/fc64b0e493ed81267c9573ef78b27523f2291018/lib/renderer.js#L33[转义]，因此会导致莫名其妙的 link:https://github.com/hcoona/hexo-renderer-asciidoc/issues[问题]出现。

另外 hexo 的 theme\next 主题中有 mathjax 的配置，将其设置为 true 后所有的页面都会引用 mathjax 的 js。

.themes/next/_config.yml
[source,yaml]
----
mathjax:
  enable: true
  per_page: false
  cdn: //cdn.bootcss.com/mathjax/2.7.1/latest.js?config=TeX-AMS-MML_HTMLorMML
----

因此开启此项配置后，结合插件，页面上的 LaTex 公式就可以正常显示了。
