----
title: 20190803_使用cgroup限制自研数据库cpu占比
categories:
- 备忘
- 技术
tags:
- 数据库
- cgroup
----

== 20190803_使用cgroup限制自研数据库cpu占比
:stem: latexmath
:icons: font

=== 背景
美国升级贸易战，为了A国业务连续性，全体产品数据库从mysql等切换自研数据库G数据库，该数据库近十年备胎之路，一朝转正，
之前没有暴露出来的问题，最近如雨后春笋，层出不穷。以前几个月发一个版本，现在一周一个版本。我们在美国宣布将XX列入实
体清单的前一个月，就已经着手G数据库的服务化，给公司去年150亿美元的产品线使用。且因为处理器和操作系统suse12被断货，我
们的版本，还涉及了自研处理器及自研操作系统的版本，问题就出在这个自研操作系统。

=== 问题表现
我们使用低版本的G数据库，在x86的处理器，及2.5版本的欧拉系统上，一切正常；
使用高版本的G数据库，在hi1620的处理器（虚拟一个4U8G的节点），及与该处理器匹配的2.8系统上，并发100的情况下，cpu就占到了99%；
通过排除法，发现使用高版本的G数据库，在x86上依然有此问题。

=== 原因及规避
在最近几个月以来，G数据库部门承受了较大的性能测试压力，因此其通过更改多种机制，榨干系统资源，满足多个业务的高性能要求；
但是我们的业务，有把数据库和其它服务，或者监控程序合设在同一个节点的场景。如果G数据库榨干了资源，其它服务均会阻塞，导致异常发生。

虽然长期来看，这个问题还是要G数据库的人员来解决，但是时间紧迫，我们目前短期的规避思路，是通过cgroup限制G数据库使用核心的时间，以及
通过提升其它关键程序的优先级，来暂时达到服务可用的目的。

=== cgroup cgconfig.conf cgrules.conf
我们首先通过手动创建/sys/fs/cgroup/cpu/g_database文件夹，并执行以下命令：

----
echo 300000 > /sys/fs/cgroup/cpu/g_database/cpu.quota.xxxx
echo 100000 > /sys/fs/cgroup/cpu/g_database/cpu.period.xxxx
# 并将进程写入该目录下的cgroup.proc及tasks
# 并执行以下命令，提高监控程序的优先级
ps -ef|grep ...|renice -15
----

来验证效果，发现问题解决。

因为服务可能频繁重启，不可能使用一个固定的进程，而在每次启动服务后获取pid并修改文件的做法，需要root权限，不符合规范。因此，我们使用cgconfig.conf和cgrules.conf来
达到目的。

网络上有大量cgroup的文章，但我们在实施过程中，遇到了一个坑。自研的欧拉系统，libcgroup-tools包中，缺失了cgred.servcie(cgsendgd二进制文件)，因此设置的cgrules.conf不生效。
无奈重新arm编译该文件，先测试，后期推动系统组件更新。

.cgconfig.conf
----
cgroup{
    cpu{
        g_database{
            cpu.quota...
            cpu.period...
        }
    }
}
----

.cgrules.conf
----
username:/opt/xxxx/command  cpu  g_database
----

使用sysbench测试，其它程序不再被G数据库阻塞，且cpu占用率稳定在我们想要的数值。