----
title: 自研数据库主备切换的一个bug记录
categories:
- 备忘
- 技术
tags:
- 数据库
- oracle
----

== 自研数据库主备切换的一个bug记录
:stem: latexmath
:icons: font

还是要给自研数据库的人点个赞，以前可能有人要问，业界有mysql，有oracle，有postgresql，大量的收费免费数据库，你们为什么要自己开发数据库？  
相信过了今年，不会再有人问这个问题了。  
自研数据库虽然具体细节不能透露，但是其只有6m的安装包大小，完美支持与oracle对接并同步的特性，兼容sql标准，支持python，c，java，  
支持多个主备，简单如mysql的配置，简单的容灾能力，支持方便的升级等等，还是很有竞争力。  

== 主备同步的bug
那么bug是什么呢？  
该数据库在一主一备的情况下，有两种手段可以进行主备倒换：
1. switchover
2. failover
switchover的场景是，如果主机和备机都正常，想手动触发主备倒换；  
failover的场景是，如果主机宕机了，备机需要容灾，提升为主机。

这个bug出现在failover的情况。在failover的场景，备机已经升为主机，但是如果主机又恢复，这个时候会出现双主的现象，就需要将其降为备（demote）。
问题是，在demote后，数据库必然出现主备不一致的情况，导致发生该数据库一个著名的异常情况needrepair，而且恢复方案需要删除数据重建，因此没人愿意写自动脚本处理，需要手工干预。

== 问题定位
我们首先快速排查自己触发切换代码，在排查后将问题范围指向该数据库本身；  
首先，主备不一致的情况，是可以在日志中查询到的。该数据库，在主机降备成功后的十秒钟左右，会打印一行类似如下的信息：
standby redo point(1/1422) is faster than primary(2/1421)，need repair...
很清晰，说新的备机redo日志比主机要快。那么就是要找出，多出来的这个操作，到底是什么？  

路线分为两路：
1. 通过解析redo日志，查看操作内容
2. 通过其它日志手段，继续确认及排查

由于环境与我们开发环境的网络较为复杂，速度也比较慢，而该redo日志有1个G，传输要1个小时。因此在等待传输的间隙，我们走路线2.

通过类似以下命令开启audit日志以及debug日志。
----
alter system set audit_level=15;
alter system set _log_level=255;
----

最终搜索通过debug日志，查到有insert语句在执行：
cat debug.log|grep -i insert -C 2

通过查询数据库的job，发现开启了wsr性能收集job：
----
select * from dba_jobs;
----

关闭该任务后，问题消失。自研数据库部门的人虽然确认问题，但是始终想不通，明明在停止和切换数据库的时间节点，已经停止wsr收集，为何还会导致该问题出现，该问题虽然不属于我们的范畴，
但是以往写并发以及过程控制要求比较严格的场景的经验告诉我，自研数据库这块的job，包括wsr以及用户自定义的job的逻辑，都需要再仔细审视一下。




