----
title: mysql 性能测试报告惨不忍睹的一次原因
categories:
- 备忘
- 技术
tags:
- mysql
----

== mysql 性能测试报告惨不忍睹的一次原因
:stem: latexmath
:icons: font

== 背景
新版本发布在即，新增与kafka，zk，redis等其它服务合设的场景，因此需要性能测试探个底。但是性能测试人员反馈，分设与合设性能差距数万倍，一句话甩过来：定位吧。

== 定位
其实干这行这么久，处理的疑难问题也不少，总结一个规律：解决别人问题，大部分精力会浪费在理清问题甚至是帮助他问问题的过程中，尤其这个人是一些强势部门或者菜鸟（菜鸟也有会思考的，但是现在很少遇到了）的情况下，例如测试。虽然提出问题的人不会提问题，但是解决问题是有科学方法遵循的。

=== 首先，明确问题----到底是什么问题
替他总结一下问题：

1. 安装两套某某版本的mysql，分别是与redis等服务合设的一套（32U64G），和mysql单独安装的一套（8U16G）。
2. 使用jmeter并且采用同样的测试模型，对服务进行长稳测试，其中合设的一套资源，其它服务也会跑长稳。
3. 观察jmeter报告，发现合设的mysql中，平均时间average为20s以上，throughput在10个/秒以下。而独立的mysql，average为ms级别，throughput为数万个。
4. 此时应该随报告提供环境cpu，磁盘，内存，网络带宽，测试模型等情况

当然，这不是我司人员的工作方法，自始至终，我们得到的情况都是误导人的。比如

1. 独立和合设的mysql，其实使用的是不同的版本。
1. 比如合设场景，没有人员进行管理，测自己组件的时候，不知道别人是不是在测试。
1. 当我们要求以管理手段对整体测试方案进行管控，对方以现网难道没有这种情况为由，拒绝同意。
1. 比如在我们咨询是否有停掉其它服务，单独在合设节点测试mysql以便控制变量，对比分设合设机器差异，我们得到的回答是很忙，哪有空给你单独测mysql。

这些都是通过辩证思维很容易得出的结论，却被人高举着“现网”的旗号强势拒绝，而其理由根本站不住脚，他要你做什么可以，你要他做什么，不行。习惯就好。

=== 其次，明确测试模型和环境----你是怎么测的，测试的时候资源情况怎么样

抛开分歧，找出原因。

该测试模型很简单，使用一个1个int主键，20个varchar（256）字段共100w的数据（sql不提供），主键还建了索引。使用select * from xxx where id in random(1, 100w);（伪代码）进行1000并发测试。

因为测试人员拒绝停止其它服务，并且无法提供独立安装的mysql环境信息，不知道如何以及收集哪些环境资源信息，不知道其它服务是否在测试，不知道mysql有没有其它人在连接。因此，我们要提早介入，主要收集以下几种信息。

* cpu及内存（top）
* iostat -x 1 以及其它 /dev/mysqllv(mysql 数据挂载磁盘)
* 查看jmeter并发服务器的jmap histro
* 查看mysql show processlist，show status like "%Thread%"等


=== 定位

正常开发会在这个阶段介入，根据信息情况，进一步定位，比如开启慢查询或者调试参数。根据以上收集的信息，发现

1. cpu，内存等资源占用不高。
2. iostat 磁盘读写速度不高，但是%util占比居高不下
3. 单独执行一条sql语句，偶尔很快，偶尔很慢
3. show processlist反馈，大量连接停留在freeing items的状态，说明连接在等候io操作，与上述iostat结论不谋而合
4. 查询审计日志，发现审计日志大量积压，5M/2分钟的速度在持续增加
4. 走管理手段，要求测试人员提供独立mysql机器信息，其反馈非其本人测试并且已卸载。我们强烈要求重新安装独立mysql
5. 独立mysql表现也慢，与合设无异（测试人员严重失误）
6. 最终发现，其独立mysql测试版本为较老版本
7. 对比版本差异，发现问题

=== 结论
新版本mysql开启audit日志，并且安全部门参照公司《mysql 安全加固规范》中的必须修改项——审计日志的策略 audit_log_strategy 必须为 `SYNCHRONOUS` , 利用自动化工具扫描并发现我们的mysql没有开启此项，提了单。修改人员在修改时因为经验不足，未多想，便直接修改。

该项的另一个可选值为ASYNCHRONOUS，即异步。与主从复制的同步，半同步及异步类似，作用不言自明。改为该值后，问题消失。





