----
title: keepalived 原理
categories:
- 备忘
- 技术
tags:
- keepalived
- vrrp
----

= Keepalived 原理


== vrrp

=== 参考：[vrrp rfc3768](https://tools.ietf.org/html/rfc3768)

The Virtual Router Redundancy Protocol (VRRP) is designed to
eliminate the single point of failure inherent in the static default
routed environment.  VRRP specifies an **election protocol** that
dynamically assigns responsibility for a virtual router to one of the
VRRP routers on a LAN.  The VRRP router controlling the IP
address(es) associated with a virtual router is called the Master,
and forwards packets sent to these IP addresses.  The election
process provides dynamic fail-over in the forwarding responsibility
should the Master become unavailable.  Any of the virtual router's IP
addresses on a LAN can then be used as the default first hop router
by end-hosts.  The advantage gained from using VRRP is a higher
availability default path without requiring configuration of dynamic
routing or router discovery protocols on every end-host.


=== 定义：

VRRP Router            A router running the Virtual Router Redundancy
                          Protocol.  It may participate in one or more
                          virtual routers.

Virtual Router         An abstract object managed by VRRP that acts
                       as a default router for hosts on a shared LAN.
                       It consists of a Virtual Router Identifier and
                       a set of associated IP address(es) across a
                       common LAN.  A VRRP Router may backup one or
                       more virtual routers.

IP Address Owner       The VRRP router that has the virtual router's
                       IP address(es) as real interface address(es).
                       This is the router that, when up, will respond
                       to packets addressed to one of these IP
                       addresses for ICMP pings, TCP connections,
                       etc.

Primary IP Address     An IP address selected from the set of real
                       interface addresses.  One possible selection
                       algorithm is to always select the first
                       address.  VRRP advertisements are always sent
                       using the primary IP address as the source of
                       the IP packet.

Virtual Router Master  The VRRP router that is assuming the
                          responsibility of forwarding packets sent to
                          the IP address(es) associated with the virtual
                          router, and answering ARP requests for these
                          IP addresses.  Note that if the IP address
                          owner is available, then it will always become
                          the Master.
Virtual Router Backup  The set of VRRP routers available to assume
                          forwarding responsibility for a virtual router
                          should the current Master fail.





